### PR TITLE
Get label for chaincode from metadata.json

### PR DESCRIPTION
**Pull request by mbwhite**
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
Can we use the new `peer lifecycle chaincode calculatepackageid`?
https://hyperledger-fabric.readthedocs.io/en/latest/commands/peerlifecycle.html#peer-lifecycle-chaincode-calculatepackageid
A PR should be coming into Fabric in next days to return the package id without any prefix that needs to be stripped off.

**Comment by mbwhite** [comment]
> Can we use the new `peer lifecycle chaincode calculatepackageid`? https://hyperledger-fabric.readthedocs.io/en/latest/commands/peerlifecycle.html#peer-lifecycle-chaincode-calculatepackageid A PR should be coming into Fabric in next days to return the package id without any prefix that needs to be stripped off.

Yes certainly - when that it's available it's a better approach...

**Comment by denyeart** [comment]
Ok, https://github.com/hyperledger/fabric/pull/3009 is merged to return the packageid.

**Review by jkneubuh — CHANGES_REQUESTED** [review]
@mbwhite can you please remove the `local` keyword from line #142?

I discovered that bash will set $? to the return code from `local`, overriding the error returned by a command within a $(shell eval).  So in this case if the user does not have jq installed, the label variable will be set to the empty string, and `errexit` will ignore the 127 error code from exec-ing jq.

**Comment by jkneubuh** [comment]
@denyeart for the new peer command, it's actually more difficult in this scope to use the new CLI option to generate the chaincode ID.  When this routine runs, it is being executed on the host OS, which may **not** actually have the peer binaries installed locally.  While this may sound draconian, it supports a much simpler workflow if we can keep the fabric binaries as optional -- all of the interaction with the Fabric network should go through the Kube APIs.

We can certainly exec into a pod running in the cluster, issue the `peer lifecycle .... calculatepackageid` command, grab the output, and ferret the results back out to the script running on the host OS.  But in this case I don't believe it's worth the benefit to justify forking the repository to retain backwards compatibility with the 2.3 line.  For this scenario I think it's more appropriate to delay the upgrade until the 2.3 / 2.4 release branches are established.

**Comment by denyeart** [comment]
Sounds good.

**Comment by mbwhite** [comment]
@jkneubuh good point.... didn't know that!

I've updated the script (and also edited the line number in your comment as Github treated it as a link to an issue :-))

**Review by jkneubuh — APPROVED** [review]

**Pull request merged**
