### PR TITLE
Update RegisterUser.java

### PR DESCRIPTION
**Pull request by dvrajitha**
Use correct identity for the appUser (Not the same admin user certificates)

### CODE REVIEW

**Comment by nikhil550** [comment]
This looks good to me, but you need to sign your commit: https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#legal-stuff

You can do that using the command `git commit --amend -s`

**Comment by dvrajitha** [comment]
@nikhil550 I have updated the commit, Now DCO check is fine. Please check

**Review by lehors — APPROVED** [review]
LGTM. Thank you!

**Comment by dvrajitha** [comment]
Awesome!!

**Pull request merged**
