### PR TITLE
Update CouchDB to 3.1.1

### PR DESCRIPTION
**Pull request by denyeart**
Update CouchDB in CI and test-network to 3.1.1.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Review by nikhil550 — APPROVED** [review]
Ran locally and everything went fine, though both on this PR and on master the ledger queries application hit this error on Init:
```
--> Submit Transaction: InitLedger, function creates the initial set of assets on the ledger
2020-10-20T21:16:13.311Z - error: [Transaction]: Error: No valid responses from any peers. Errors:
    peer=peer0.org2.example.com:9051, status=500, message=error in simulation: transaction returned with failure: Error: GET_STATE failed: transaction ID: 8c0b4104f79268f4042ad89c2ad5eca82f643ccf58203d308267dedbc5433997: no revision tag detected
```

**Comment by denyeart** [comment]
@nikhil550 The checks in this PR show success on all the tests. Or do I need to dig into the actual logs to see the issue?

I also tried locally and see no such issue.  Exactly which test are you running?  Does the problem occur with couchdb 3.1 and couchdb 3.1.1 for you?

**Comment by nikhil550** [comment]
@denyeart The error I hit was on Ubuntu on windows, running javascript application and chaincode. The error was on 3.1.1 and 3.1 both, so not related to this PR.

**Comment by denyeart** [comment]
@nikhil550 ok, i'm not seeing it... can you turn on debug and send to me:

FABRIC_LOGGING_SPEC=info:kvledger,statecouchdb,couchdb=debug

In the meantime, I'll go ahead and merge this PR.

**Comment by nikhil550** [comment]
Ran this on MacOS. everything worked with golang chaincode (which is what the tests used), but failed using the javascript chaincode.

Looking at the logs, it seems to be a chaincode error:
```
2020-10-23 14:40:42.385 UTC [endorser] callChaincode -> INFO 0ad finished chaincode: ledger duration: 35ms channel=mychannel txID=2f53db7f
2020-10-23 14:40:42.385 UTC [endorser] SimulateProposal -> ERRO 0ae failed to invoke chaincode ledger, error: transaction returned with failure: Error: object type or attribute not a non-zero length string
```

**Pull request merged**
