### PR TITLE
fix ccp template and generator to include orderer and channel

### PR DESCRIPTION
**Pull request by nasermirzaei89**
Update ccp template and generator to include orderer and channel.
needed for `asset-transfer-basic/application-go/assetTransfer.go`

Signed-off-by: Naser Mirzaei <nasermirzaei89@gmail.com>

### CODE REVIEW

**Comment by nikhil550** [comment]
The simplified connection profile is best practice when using service discovery, which we encourage. May be better to create another ccp specifically for the go application, rather than update the connection profile used by all of them.

**Comment by nasermirzaei89** [comment]
> This should not be required when using the gateway GO.
> 
> Is there a failure that needs to addressed in this sample or the gateway GO package ?

when I try to run `asset-transfer-basic/application-go/assetTransfer.go` it tells:
`SendTransaction failed: orderers is nil`

More info at https://stackoverflow.com/questions/62927393/hyperledger-2-2-fabcar-transaction-issue

**Review by andrew-coleman — CHANGES_REQUESTED** [review]
This should not be needed for any of the 'gateway' SDKs.
Do you have the DISCOVERY_AS_LOCALHOST env-var set to "TRUE"?

**Comment by nikhil550** [comment]
I think we have agreed that this pull request could be closed. To fix this bug, rather than changing the main connection profiles, we should
1) update the Go code or SDK to allow it to make use of the connection profiles used by the other SDK's
or 
2) If that is not possible, create a new connection profile that can be used by go applications.

**Comment by andrew-coleman** [comment]
Just to clarify, the Go SDK gateway package _does_ support the same connection profile as the other SDKs.  The fabcar sample (now deprecated) used this same network as this and works.  The fabcar sample gets run as part of the CI pipeline.

**Pull request closed without merging**
