### PR TITLE
off_chain_data - Error when run command "node blockEventListener.js"

### PR DESCRIPTION
**Pull request by manish1635**
https://jira.hyperledger.org/browse/FABN-1449

### CODE REVIEW

**Comment by manish1635** [comment]
> I suspect you didn't intend to change 200+ file!

Yes, I would like to change a single file "blockProcessing.js".  please give me access.

**Comment by nikhil550** [comment]
Some of these errors may be fixed in this PR: https://github.com/hyperledger/fabric-samples/pull/122

I ran into SDK changes when updated the sample to run on test network.

**Comment by lehors** [comment]
Hi @manish1635, do you plan to update this PR?
I'm not quite sure what you mean by giving you access to the one file you meant to change but your PR includes changes to many other files and *you* need to fix that by updating your PR. Your PR should only include changes to the one file you actually want to modify.
Please, also @nikhil550's comment and confirm what actually needs fixing.
Thank you for your contribution.

**Comment by lehors** [comment]
Looking at this again I realized that this PR is really broken. It is trying to merge commits from release-1.4 into master when what is needed is a merge into release-1.4. I will close it and resubmit.
@manish1635, thanks for pointing out the problem with the samples though. This problem is fixed on master by the way.

**Pull request closed without merging**
