### PR TITLE
Add type parameters

### PR DESCRIPTION
**Pull request by suraneti**
If you accept this PR please add `hacktoberfest-accepted` label on this PR.

Signed-off-by: Suraneti Rodsuwan <suraneti.rod@gmail.com>

### CODE REVIEW

**Comment by lehors** [comment]
Hi,
Can you please explain what the point of that change is? (other than trying to land a PR for the Hacktoberfest ;-)
The way the code is currently written is perfectly legal Go code and doesn't even trigger any warning or similar from golint.

**Comment by suraneti** [comment]
Hello,
I agree with you that the code is working perfectly but I think it would be good to make all function look the same code style, 
 some function parameters have a type but some haven't.

Ex.1 this func `assetID` parameter has type.
```Go
func (t *SimpleChaincode) AssetExists(ctx contractapi.TransactionContextInterface, assetID string) (bool, error) {
...
}
```

Ex.2 this func `assetID` parameter doesn't have type.
```Go
func (t *SimpleChaincode) TransferAsset(ctx contractapi.TransactionContextInterface, assetID, newOwner string) error {
...
}
```

P.S. I'm starting studying HyperLedger Fabric tutorial with Golang.

**Comment by denyeart** [comment]
Thank you for the contribution, but all parameters have a type already - in Go it is idiomatic to not repeat the parameter type for multiple parameters in a row that have the same type.
Therefore let's Close this PR.

**Comment by denyeart** [comment]
I just checked asset-transfer-basic and I forgot that it actually does enumerate the type for each of the parameters, so this PR would make the samples consistent. My apologies @suraneti ... I do agree it would be good to be consistent and I'm open to discussion on which approach is best.

**Comment by suraneti** [comment]
@denyeart Thank you for the explanation and rechecking, Have a great day.

**Pull request closed without merging**
