### PR TITLE
ERC1155: subtraction overflow issue resolved

### PR DESCRIPTION
**Pull request by rajat-dlt**
This resolves issue #765.
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>

### CODE REVIEW

**Comment by rajat-dlt** [comment]
@denyeart, could you please look into this PR and let me know if any further changes are needed on this.

**Comment by denyeart** [comment]
Thanks @rajat-dlt . Could you also fix the same problem at https://github.com/hyperledger/fabric-samples/blob/main/token-erc-20/chaincode-go/chaincode/token_contract.go#L724 in this PR?

These issues that you are finding all got introduced in https://github.com/hyperledger/fabric-samples/pull/731.  I think that PR tried to do too much in a single commit and therefore these problems were not caught. This is a good reminder that we should do smaller PRs with a single change and re-test each of the chaincodes (Ideally these chaincodes should have CI tests similar to the asset-transfer CI tests).

@fraVlaca I believe you are re-visiting the samples as well... please double check each of them and re-test to make sure they are working per the readmes.

**Comment by rajat-dlt** [comment]
@denyeart, the fix is added for ERC20.

**Comment by denyeart** [comment]
Thanks Rajat!

**Pull request merged**
