### PR TITLE
[FAB-17268] Move fabcar sample to test network

### PR DESCRIPTION
**Pull request by nikhil550**
Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>

Moving fabcar from byfn to the new test network.
- Using the CAs supported natively by the test network
- Using the scripts provided by the test network and remove the chaincode deployment in `startFabric.sh`
- Change connection profile path
- user1 > appUser since user 1 is already registered with the CA
- Adding a `stopFabric.sh` script so users do not have to change directories.

Related Issues:
This update to the sample corresponds to this update to the first app tutorial: https://github.com/hyperledger/fabric/pull/522
The two should be merged together.

### CODE REVIEW

**Comment by robmurgai** [comment]
@nikhil550 In the description I see user1 > fabcarUser since user 1 is already registered with the CA, . . in RegisterUser.java, invoke.js  I see the user listed as "appuser".

**Comment by nikhil550** [comment]
> @nikhil550 In the description I see user1 > fabcarUser since user 1 is already registered with the CA, . . in RegisterUser.java, invoke.js I see the user listed as "appuser".

I originally had fabcarUser, but changed it to a better name for the tutorial. Forgot to update the PR comment.

**Pull request merged**
