### PR TITLE
Ensure that Java examples are at 2.5.0

### PR DESCRIPTION
**Pull request by mbwhite**
And remove examples that incorrectly use internal protos

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

### CODE REVIEW

**Comment by jkneubuh** [comment]
grade 7 needs an upgrade from `compile` to `implementation` directives for the digibank/contract-java.  This passes a local build / lint with jdk11 and the gradlew 7.4.2: 
```
dependencies {
    implementation 'org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.5.+'
    implementation 'org.json:json:+'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.4.2'
    testImplementation 'org.assertj:assertj-core:3.11.1'
    testImplementation 'org.mockito:mockito-core:2.+'
}
```

**Comment by mbwhite** [comment]
@jkneubuh sorry confused - I thought the gradle files where already using the `implementation` ?  Compile is deprecated is it not?

**Comment by jkneubuh** [comment]
Yes, `compile` is now removed, not just deprecated.   Still one straggler in the citibank contract-java.  I ran this locally on the sbe-java-update branch and it passes the linter: 
```
(base) jkneubuh@gala contract-java % git diff 
diff --git a/commercial-paper/organization/digibank/contract-java/build.gradle b/commercial-paper/organization/digibank/contract-java/build.gradle
index 6574187..051785b 100644
--- a/commercial-paper/organization/digibank/contract-java/build.gradle
+++ b/commercial-paper/organization/digibank/contract-java/build.gradle
@@ -18,8 +18,8 @@ repositories {
 }
 
 dependencies {
-    compileOnly group: 'org.hyperledger.fabric-chaincode-java', name: 'fabric-chaincode-shim', version: '2.+'
-    compile group: 'org.json', name: 'json', version: '20180813'
+    implementation 'org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.5.+'
+    implementation 'org.json:json:+'
     testImplementation 'org.junit.jupiter:junit-jupiter:5.4.2'
     testImplementation 'org.assertj:assertj-core:3.11.1'
     testImplementation 'org.mockito:mockito-core:2.+'
```

**Review by lehors — COMMENTED** [review]
LGTM overall, I have one question on the removal of some quotes.

**Pull request closed without merging**
