### PR TITLE
GetID to return clientId in base64 form

### PR DESCRIPTION
**Pull request by knarayan**
Signed-off-by: Krishnasuri Narayanam <knaraya3@in.ibm.com>

### CODE REVIEW

**Review by mbwhite — COMMENTED** [review]
Hello - could I check why the cast here... the clientIdentity interface returns a string already does it not?

https://github.com/hyperledger/fabric-chaincode-go/blob/7bc6fa0dd58be10ef9fa2a0452355b855c7bcad3/pkg/cid/interfaces.go#L23

**Comment by lehors** [comment]
@knarayan Could you please followup and respond to @mbwhite ? Thanks.

**Comment by knarayan** [comment]
@mbwhite Since GetID is returning base64 encoded string ( https://github.com/hyperledger/fabric-chaincode-go/blob/7bc6fa0dd58be10ef9fa2a0452355b855c7bcad3/pkg/cid/cid.go#L106 ), the test case also expects the same to be returned by the mocking function `GetIDReturns`. Hence the change. Without this the test cases were failing and here is the log for your reference #770 .

**Review by lehors — DISMISSED** [review]
Thank you for your PR and sorry for the long delay merging it.
I tested it and you are correct.

**Pull request merged**
