### PR TITLE
Revert #118

### PR DESCRIPTION
**Pull request by btl5037**
This reverts commit 9ef61e2d7204964ad02b53b171c05f87a673e42d.

Introduced regressions when running without explicitly specifying
a chaincode label

### CODE REVIEW

**Comment by SirineHml** [comment]
===================== Anchor peers updated for org 'Org2MSP' on channel 'mychannel' ===================== + peer lifecycle chaincode package mycc.tar.gz --path github.com/hyperledger/fabric-samples/chaincode/abstore/go/ --lang golang --label mycc_1 + res=1 + set +x

!!!!!!!!!!!!!!! Chaincode packaging on peer0.org1 has failed !!!!!!!!!!!!!!!! ========= ERROR !!! FAILED to execute End-2-End Scenario ===========

ERROR !!!! Test failed 

Any one can help me :( !!!!!!

**Comment by adeebabdulsalam** [comment]
Channel name : mychannel
+ peer lifecycle chaincode package mycc.tar.gz --path github.com/hyperledger/fabric-samples/chaincode/fabcar/go/ --lang golang --label mycc_1
+ res=1
+ set +x
2020-05-28 19:58:23.500 UTC [bccsp] GetDefault -> DEBU 001 Before using BCCSP, please call InitFactories(). Falling back to bootBCCSP.
2020-05-28 19:58:23.512 UTC [bccsp] GetDefault -> DEBU 002 Before using BCCSP, please call InitFactories(). Falling back to bootBCCSP.
2020-05-28 19:58:23.514 UTC [main] InitCmd -> DEBU 003 peer lifecycle chaincode package does not need to init crypto
Error: error getting chaincode bytes: failed to calculate dependencies: incomplete package: github.com/hyperledger/fabric-contract-api-go/contractapi
!!!!!!!!!!!!!!! Chaincode packaging on peer0.org1 has failed !!!!!!!!!!!!!!!!
========= ERROR !!! FAILED to execute End-2-End Scenario ===========

Still have the issue, fabric version 2.1

**Comment by lehors** [comment]
@adeebabdulsalam We should have responded to @SirineHml but what makes you think the error you're facing has anything to do with what this PR was about?
I don't think it does and can't reproduce it. I suggest you ask for help on the fabric list, providing more context as to what you are doing that leads to this error. Are you running fabcar/startFabric.sh?

**Comment by nerotiger** [comment]
> ===================== Anchor peers updated for org 'Org2MSP' on channel 'mychannel' ===================== + peer lifecycle chaincode package mycc.tar.gz --path github.com/hyperledger/fabric-samples/chaincode/abstore/go/ --lang golang --label mycc_1 + res=1 + set +x
> 
> !!!!!!!!!!!!!!! Chaincode packaging on peer0.org1 has failed !!!!!!!!!!!!!!!! ========= ERROR !!! FAILED to execute End-2-End Scenario ===========
> 
> ERROR !!!! Test failed
> 
> Any one can help me :( !!!!!!

I have the same problem, did you find a cure?

**Comment by SirineHml** [comment]
I did not fix it, I change the platform hyperledger and now I use ethereum..

**Pull request merged**
