### PR TITLE
Update fabric version

### PR DESCRIPTION
**Pull request by btl5037**
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>

### CODE REVIEW

**Comment by btl5037** [comment]
@mbwhite @sstone1 While doing artifactory work, I discovered 1.4 CI was still using 1.4.4-stable images instead of 1.4.5-stable. There are errors in both java and typescript chaincode, I don't have the cycles to dig into this right now, this PR contains both of the failures

**Comment by btl5037** [comment]
This isn't going to pass, someone needs to take a look at why 1.4.5 doesn't work with Samples, I unfortunately don't have the cycles at the time to look into it

**Comment by lehors** [comment]
Ok, I'm going to override the CI failure because it has nothing to do with this PR.

**Comment by ryjones** [comment]
shouldn't these have been artifactory urls?

**Comment by lehors** [comment]
There is another PR to change to artifactory (#93) but it's true that this may render this PR moot...

**Pull request merged**
