### PR TITLE
is the parameter -ca -s couchdb must set up

### PR DESCRIPTION
**Pull request by SamYuan1990**
Signed-off-by: SamYuan1990 <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
trigger this pr for cicd build, as we using fabric sample for our cicd jobs which fails creating channel.
https://dev.azure.com/guojiannan1101/Tape/_build/results?buildId=474&view=logs&jobId=000c3020-69c7-583a-2317-12a3c1cc0703&j=000c3020-69c7-583a-2317-12a3c1cc0703&t=49e496f5-3370-599b-f40e-d06821c04293

**Comment by SamYuan1990** [comment]
2 questions：
Q1: does 2.3 binary supports 2.2 images？ as https://dev.azure.com/Hyperledger/Fabric-Samples/_build/results?buildId=25956&view=logs&j=da384fcf-90d4-5b80-43e1-e99336f28a8e&t=b9765d42-0282-54df-8521-24ae18744699
the 2.3 binary breaks 2.2 orderer with channel creataion?

Q2: does `-ca -s couchdb` must used to start a network?

**Comment by lehors** [comment]
No, the parameters -ca -s couchdb don't have to be set for a Fabric network to run. These are options we use in our samples.
I'm not aware of any incompatibilities between 2.3 and 2.2 but I haven't tried the combination you are talking about.
Please, do not use the PR process to ask questions. Questions are best asked on the fabric mailing or one of the RocketChat channels such as #fabric-samples.
Thanks.

**Comment by SamYuan1990** [comment]
> No, the parameters -ca -s couchdb don't have to be set for a Fabric network to run. These are options we use in our samples.
> I'm not aware of any incompatibilities between 2.3 and 2.2 but I haven't tried the combination you are talking about.
> Please, do not use the PR process to ask questions. Questions are best asked on the fabric mailing or one of the RocketChat channels such as #fabric-samples.
> Thanks.

Hi @lehors , thanks for reply this pr. 
I am agree with u that pr is not designed for this kind of things. so this reply I just do some clarify.

1. I did asked in chat. over 2 hours. from 22:35 BTJ to 24:00 BJT(10:35pm to midnight) without any feed back. for both fabric-sample and fabric-question, and general... 
image

2. well, yep you may not hearing any thing about 2.3 and 2.2 incompatibilities. but which doesn't mean there is not. people have new founding everyday. I found a combination for 2.3 and 2.2 that you haven't tried. And reproduced via azp pipeline. If you had look at azp pipeline for this pr. with line 21 and below https://dev.azure.com/Hyperledger/Fabric-Samples/_build/results?buildId=25956&view=logs&j=da384fcf-90d4-5b80-43e1-e99336f28a8e&t=b9765d42-0282-54df-8521-24ae18744699&l=21
we will have azp helped us run this combination and reporting.

thanks and regards
Sam

**Comment by guoger** [comment]
This pr is merely to demonstrate potential incompatibility, which is referenced in the chat/jira. It probably could've been titled with a more clear message to avoid confusion.

Back to the topic, this specific "incompatibility" was caused by falsely applying configs (more specifically `orderer.yaml`) from *master* to *2.2* images. Newly introduced `ChannelParticipation` is not recognized by 2.2 orderer and triggers panic. One should pull release tar with correct/matching version to get it work.

@SamYuan1990 thx for putting effort in reproducing and reporting the problem

**Comment by lehors** [comment]
Thanks for the clarification @guoger . Are you fixing the orderer so that it deals more gracefully with configuration settings it doesn't recognize? This seems like a must to be future proof.

**Comment by lehors** [comment]
@SamYuan1990 The change was reversed, please, let us know if you see any other problems.
Thanks.

Note: It's Thanksgiving in the US and many people are out on vacation. So while I understand that waiting for a response isn't pleasant "over 2 hours" isn't really long, especially during a holiday. :-)

**Comment by SamYuan1990** [comment]
> @SamYuan1990 The change was reversed, please, let us know if you see any other problems.
> Thanks.
> 
> Note: It's Thanksgiving in the US and many people are out on vacation. So while I understand that waiting for a response isn't pleasant "over 2 hours" isn't really long, especially during a holiday. :-)

Thanks @lehors , just remembered that today is Thanksgiving. May I say "Thanks giving us with open source and thanks giving with fabric!" Enjoy & Cheers.

Sorry for misunderstanding about the title. Em... a maintainer of TWGC, https://github.com/Hyperledger-TWGC, I'd better attend global meeting to learn and know more, as from local to global :-)

I am now plan to join Fabric Contributor Meeting, according to my job schedule, hope no conflicts. Hope I am able to start this plan in coming weeks.

**Pull request closed without merging**
