### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pushp1997**
In the fabric-samples/full-stack-asset-transfer-guide/docs/ApplicationDev/01-FabricGateway.md file, there is a spelling error in the section 'Production deployment of Fabric Gateway', in last line of second paragraph. 'atually' should presumably be 'actually' (missing a 'c').

### CODE REVIEW

**Comment by satota2** [comment]
@pushp1997 Thanks for the contribution.
Could you fix the DCO problem?

The following command will probably fix this problem.
`git commit --amend -s`
(You can add a Signed-off-by line in your original commit message automatically by using the above command.)

[Please check here for more information on the DCO problem](https://github.com/hyperledger/fabric-samples/pull/1048/checks)

**Review by satota2 — CHANGES_REQUESTED** [review]
@pushp1997 Thanks for the contribution.
Could you fix the DCO problem?

The following command will probably fix this problem.
`git commit --amend -s`
(You can add a Signed-off-by line in your original commit message automatically by using the above command.)

[Please check here for more information on the DCO problem](https://github.com/hyperledger/fabric-samples/pull/1048/checks)

Other than that, it looks good.

**Comment by pushp1997** [comment]
Hi @satota2, I have fixed the DCO problem, could you please merge the changes? Let me know if anything else is required at my end, will be happy to help.

**Review by satota2 — APPROVED** [review]

**Review by satota2 — APPROVED** [review]
@pushp1997 Thank you for fixing. LGTM!

**Review by lehors — APPROVED** [review]

**Pull request merged**
