### PR TITLE
Add init function to avoid init function not found error

### PR DESCRIPTION
**Pull request by SamYuan1990**
Hi 

Recently I followed https://hyperledger-fabric.readthedocs.io/en/release-2.1/private_data_tutorial.html#commit-the-chaincode-definition
with master branch of fabric-sample.

An error happen when I attempted to init the chaincode with function init
```
 peer chaincode invoke -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --channelID mychannel --name marblesp --isInit --tls --cafile $ORDERER_CA --peerAddresses localhost:7051 --tlsRootCertFiles $ORG1_CA -c '{"Args":["Init"]}'
```
```
Error: endorsement failure during invoke. response: status:500 message:"error in simulation: transaction returned with failure: Function Init not found in contract SmartContract" 
```

Here is the fix for this with adding `function Init`, please verify.

Signed-off-by: SamYuan1990 <yy19902439@126.com>

### CODE REVIEW

**Comment by davidkhala** [comment]
If the definition of the chaincode is not init_required, then there is no need to call init function before regular usage. 

While I have not yet check the tutorial setting

**Comment by SamYuan1990** [comment]
> If the definition of the chaincode is not `init_required`, then there is no need to call init function before regular usage.
> 
> I see in tutorial `--init-required` is used so Init function should be added.

So, I suppose either update the code or the tutorial,

as there is `--init-required` https://hyperledger-fabric.readthedocs.io/en/release-2.1/private_data_tutorial.html#commit-the-chaincode-definition
```
peer lifecycle chaincode commit -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --channelID mychannel --name marblesp --version 1.0 --sequence 1 --collections-config ../chaincode/marbles02_private/collections_config.json --signature-policy "OR('Org1MSP.member','Org2MSP.member')" --init-required --tls --cafile $ORDERER_CA --peerAddresses localhost:7051 --tlsRootCertFiles $ORG1_CA --peerAddresses localhost:9051 --tlsRootCertFiles $ORG2_CA
```

**Comment by nikhil550** [comment]
Hi @SamYuan1990, thank you for finding this. The code was updated, but the `--init-required` was left in the tutorial. Since we are trying to move folks away from Init, I would rather update the tutorial rather than the code.

**Comment by SamYuan1990** [comment]
> Hi @SamYuan1990, thank you for finding this. The code was updated, but the `--init-required` was left in the tutorial. Since we are trying to move folks away from Init, I would rather update the tutorial rather than the code.

Either fine for me. Pls let me know for pr of the tutorial upgrade. thx.

**Comment by SamYuan1990** [comment]
> Hi @SamYuan1990, thank you for finding this. The code was updated, but the `--init-required` was left in the tutorial. Since we are trying to move folks away from Init, I would rather update the tutorial rather than the code.

https://github.com/hyperledger/fabric/pull/1405

**Comment by mbwhite** [comment]
@nikhil550  I'm happy with this.. is ok from your perspective to merge?

**Comment by nikhil550** [comment]
@mbwhite Dave and I have actually been trying to move people away from the Init behavior. The tutorial actually contains the changes required to run the chaincode as is in latest. However the cherry-picks of those changes into 2.1 and 2.0 are being held up by a CI problem:
https://github.com/hyperledger/fabric/pull/1402
https://github.com/hyperledger/fabric/pull/1401

Once those are merged, all will be good.

**Pull request closed without merging**
