### PR TITLE
test-network-k8s : Connect to Fabric services via Nginx Ingress - READY FOR MERGE

### PR DESCRIPTION
**Pull request by jkneubuh**
This PR updates the Kube test network to access Fabric services via an Ingress controller.  This allows for easy access to the CAs, peers, orderers, and load-balanced Gateway Peer via the nginx bound to localhost:443.

In previous iterations, any administration of the network involved a remote exec to execute commands on an "admin CLI pod" running in the cluster.  In addition, any time files needed to get to/from the volume mounts in Kubernetes, an overly complicated sequence of arcane `exec tar --.... ` commands was necessary.

With this PR, the network is instantiated, exposing core services at the *.vcap.me (wildcard match to 127.0.0.1) DNS domain.  Fabric binaries are run directly on the host, and certificate enrollments are managed locally as if they were maintained in a local wallet storage.

### CODE REVIEW

**Comment by jkneubuh** [comment]
Addresses Issue #685

This PR is generally in good shape for a peer review.

There is still some errant flakiness when accessing the CA to determine the ECert signing certificate.  On occasion the Nginx ingress (or possibly the org CA) is returning an empty body from the /cainfo URL, leading to an empty ca-cert.pem.  Adding a slight delay between issuing setup commands seems to work around the issue.   If the network or test suite is run as a single copy/paste command, or in quick succession, it will occasionally flake.  I'll track this down before removing the DRAFT PR status.

**Comment by mbwhite** [comment]
Test with Ubuntu image running WSL2 commencing...

- Fabric binary is 2.4.2.. (2.4.3 is the latest)

**Review by mbwhite — COMMENTED** [review]
@jkneubuh `vcap.me` needs mapping to `127.0.0.1`  is this documented in the readme?

**Comment by jkneubuh** [comment]
No *.vcap.me is a "real thing."  This was set up by VMWare to help ... access vm services running on a loopback with a DNS wildcard.  The alias does NOT need any local configuration - it should be handled OK with public DNS.  Are you having issues resolving this with BT?

If this approach "sticks" it would be nice to set up an alternative, more friendly name, managed by Hyperledger Foundation or an enterprise sponsor of the project.  For instance, publish a PUBLIC DNS A / wildcard record : 

*.loopback.fabric.hyperledger.org --> 127.0.0.1 

vcap.me gets the job done OK, but the name is not ideal...

**Comment by mbwhite** [comment]
wow - did not know that...  you learn something new every day... yes `vcap.me` does work for me. 

And here's me thinking 'must ask Josh why he's chosen such an odd name,'

**Pull request merged**
