### PR TITLE
GetHistoryForKey added to the chaincode-typescript

### PR DESCRIPTION
**Pull request by ajiths10**
Added a chaincode transaction to retrieve the complete history of an asset using its asset ID.

### CODE REVIEW

**Review by satota2 — COMMENTED** [review]
@ajiths10 Thank you for submitting the PR.

Since asset-transfer-basic is the most fundamental sample, it should provide only the minimal necessary functions. Adding your proposed GetHistoryForKey to this sample might be too advanced.

If you believe that a sample TypeScript implementation of GetHistoryForKey is necessary, it would be more appropriate to implement the TypeScript version of the [asset-transfer-ledger-queries](https://github.com/hyperledger/fabric-samples/tree/a1b5f6830dd3ba38f7c9f139f065e8d65c94b88a/asset-transfer-ledger-queries) sample, as it already includes the GetHistoryForKey functionality. What do you think about this approach?

**Comment by denyeart** [comment]
> @ajiths10 Thank you for submitting the PR.
> 
> Since asset-transfer-basic is the most fundamental sample, it should provide only the minimal necessary functions. Adding your proposed GetHistoryForKey to this sample might be too advanced.
> 
> If you believe that a sample TypeScript implementation of GetHistoryForKey is necessary, it would be more appropriate to implement the TypeScript version of the [asset-transfer-ledger-queries](https://github.com/hyperledger/fabric-samples/tree/a1b5f6830dd3ba38f7c9f139f065e8d65c94b88a/asset-transfer-ledger-queries) sample, as it already includes the GetHistoryForKey functionality. What do you think about this approach?

Makes sense to me. Note that there is a chaincode-javascript [reference with GetHistoryForKey() ](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js#L301)that can be used as reference. Ideally the various languages would have the same support in the asset-transfer-ledger-queries.

**Comment by ajiths10** [comment]
Hi @satota2 ,

I believe **GetHistoryForKey** is a fundamental function available in many other languages, including JavaScript. Adding this functionality to TypeScript would be highly beneficial and valuable to the TypeScript community. Since I found it challenging to locate this code in community spaces, I decided to include it in a TypeScript sample myself.

What are your thoughts?

**Comment by satota2** [comment]
@ajiths10 

Thank you for your response.

While GetHistoryForKey is indeed a fundamental function as you mentioned, compared to the basic asset CRUD and transfer operations handled in asset-transfer-basic, its general usage frequency are relatively lower. Therefore, as I previously mentioned, I believe adding it to this simple scenario sample might be too much.

On the other hand, I agree that having a TypeScript sample for GetHistoryForKey would be very beneficial. So, as I previously suggested, I propose implementing a TypeScript version of the asset-transfer-ledger-queries sample. This sample includes other ledger query functionalities in addition to GetHistoryForKey, making it more valuable for TypeScript users.

Regarding the difficulty in finding the GetHistoryForKey functionality, I agree that it needs improvement. As a potential solution, including a note in the asset-transfer-ledger-queries description that mentions it contains GetHistoryForKey might help navigate users better.

 What do you think?

**Comment by ajiths10** [comment]
> @ajiths10
> 
> Thank you for your response.
> 
> While GetHistoryForKey is indeed a fundamental function as you mentioned, compared to the basic asset CRUD and transfer operations handled in asset-transfer-basic, its general usage frequency are relatively lower. Therefore, as I previously mentioned, I believe adding it to this simple scenario sample might be too much.
> 
> On the other hand, I agree that having a TypeScript sample for GetHistoryForKey would be very beneficial. So, as I previously suggested, I propose implementing a TypeScript version of the asset-transfer-ledger-queries sample. This sample includes other ledger query functionalities in addition to GetHistoryForKey, making it more valuable for TypeScript users.
> 
> Regarding the difficulty in finding the GetHistoryForKey functionality, I agree that it needs improvement. As a potential solution, including a note in the asset-transfer-ledger-queries description that mentions it contains GetHistoryForKey might help navigate users better.
> 
> What do you think?


@satota2  ,
Yes, that sounds good!

**Comment by satota2** [comment]
@ajiths10 Thank you for agreeing.
I have created two issues based on the above discussion, so I would like to close this PR.
- https://github.com/hyperledger/fabric-samples/issues/1232
- https://github.com/hyperledger/fabric-samples/issues/1233

If you are interested in helping resolve these issues, I would greatly appreciate your collaboration.
Would you be willing to help?

**Comment by ajiths10** [comment]
> @ajiths10 Thank you for agreeing. I have created two issues based on the above discussion, so I would like to close this PR.
> 
> * [Add TypeScript version of asset-transfer-ledger-queries chaincode #1232](https://github.com/hyperledger/fabric-samples/issues/1232)
> * [Improve documentation to highlight GetHistoryForKey support in asset-transfer-ledger-queries #1233](https://github.com/hyperledger/fabric-samples/issues/1233)
> 
> If you are interested in helping resolve these issues, I would greatly appreciate your collaboration. Would you be willing to help? Of course, even if you can assist with just one of the issues, it would be very welcome.

@satota2 Thanks for addressing this. I look forward to it.

**Comment by satota2** [comment]
@ajiths10 OK. I close this PR.
If you are interested in taking on any of these issues, please leave a comment on the respective issue. I will then assign the issue to you. This will help avoid duplicate work by other comunity members (including possibly myself) on the same issue.

**Pull request closed without merging**
