### PR TITLE
res=$? missing

### PR DESCRIPTION
**Pull request by tyanj**
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
Signed-off-by: tyanj <653291675@qq.com>

### CODE REVIEW

**Comment by lehors** [comment]
I'm reverting the removal of typescript, @tyanj once this is completed you will need to rebase your PR.
Thanks.

**Comment by btl5037** [comment]
This was just a bad rebase. Can you do a `git fetch <your upstream> && git rebase <your upstream>/master` to fix this bad rebase

**Comment by lehors** [comment]
@tyanj Are you going to fix this PR? Otherwise I will close it and submit a new one with your change.
Thanks.

**Comment by lehors** [comment]
Ok, I asked @ryjones to use his github skills to fix this PR. I will merge it. Thanks Ry!

**Pull request merged**
