### PR TITLE
Fixed sdk connection bugs "SendTransaction failed: orderers is nil", make it fit the "entityMatchers" way.

### PR DESCRIPTION
**Pull request by user00000001**
Signed-off-by: 暾暾 <631078133@qq.com>

### CODE REVIEW

**Comment by rijulaggarwal16** [comment]
I'm trying to reproduce the error to verify this fix. Can you tell which command exactly fails on the network? I've gone through all documented commands for the test-network which submit and evaluate transactions. Thanks.

**Comment by user00000001** [comment]
invoke way likes below:
```go
ccpPath := filepath.Join("./connection.yml")
c := config.FromFile(ccpPath)
sdk, err := fabsdk.New(c)
clientChannelContext := sdk.ChannelContext(channelName, fabsdk.WithUser(orgAdmin), fabsdk.WithOrg(orgName))
client, err := channel.New(clientChannelContext)
```

connection.yml likes below:
```yaml
version: 1.0.0
client:
  organization: Org1
  logging:
    level: info
  cryptoconfig:
    path: ./organizations
  credentialStore:
    path: "./tmp/state-store"
    cryptoStore:
      path: ./organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256
  tlsCerts:
    systemCertPool: true
channels:
  _default:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 8
        peerMonitorPeriod: 6s
  mychannel:
    # orderers:
    #   - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath:  ./organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    peers:
      - peer0.org1.example.com
    users:
      Admin:
        cert:
          path: ./organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
      User1:
        cert:
          path: ./organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem

orderers: #这部分内容没有起作用，原因未知 ==> 需要在channels内具体channel内部指定orderers列表
  orderer.example.com:
    url: orderer.example.com:7050
    tlsCACerts:
      path: ./organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
      hostnameOverride: orderer.example.com
peers:
  peer0.org1.example.com:
    url: peer0.org1.example.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ./organizations/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
  peer0.org2.example.com:
    url: peer0.org2.example.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ./organizations/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      path: ./organizations/fabric-ca/org1/tls-cert.pem
    httpOptions:
      verify: false
entityMatchers:
  peer:
    - pattern: (\w+).org1.example.com:(\d+)
      urlSubstitutionExp: ${1}.org1.example.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.example.com
      mappedHost: peer0.org1.example.com
    - pattern: (\w+).org2.example.com:(\d+)
      urlSubstitutionExp: ${1}.org2.example.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.example.com
      mappedHost: peer0.org2.example.com
  orderer: # 使其起作用需要在configtx.yaml内Orderer项下增加Addresses列表，同时不再需要本配置mychannel下指定orderers
    - pattern: (\w+) #理论上该写(\w+).example.(\w+)，但总是访问127.0.0.1:7050,暂时未找到原因，先模糊匹配
      urlSubstitutionExp: orderer.example.com:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com
```
It is similar with #303 #311 when submit something to blockchain, but I find the a better way to fix it now.

**Comment by rijulaggarwal16** [comment]
This gave me some problems when running. Not sure if it's specific to your solution though.

I was able to reproduce the problem:
image

But upon using this solution, I get:
```
 ============ application-golang starts ============
2020/09/15 10:16:57 ============ Populating wallet ============
 [fabsdk/core] 2020/09/15 14:16:57 UTC - cryptosuite.GetDefault -> INFO No default cryptosuite found, using default SW implementation
2020/09/15 10:16:57 Failed to get network: Failed to create new channel client: event service creation failed: could not get chConfig cache reference: QueryBlockConfig failed: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:7051]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection on target [localhost:7051]: connection is in TRANSIENT_FAILURE
exit status 1
```

**Comment by user00000001** [comment]
> This gave me some problems when running. Not sure if it's specific to your solution though.
> 
> I was able to reproduce the problem:
> image
> 
> But upon using this solution, I get:
> 
> ```
>  ============ application-golang starts ============
> 2020/09/15 10:16:57 ============ Populating wallet ============
>  [fabsdk/core] 2020/09/15 14:16:57 UTC - cryptosuite.GetDefault -> INFO No default cryptosuite found, using default SW implementation
> 2020/09/15 10:16:57 Failed to get network: Failed to create new channel client: event service creation failed: could not get chConfig cache reference: QueryBlockConfig failed: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:7051]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection on target [localhost:7051]: connection is in TRANSIENT_FAILURE
> exit status 1
> ```

Add "entityMatchers" configuration into your "connection.yml" file, "entityMatchers" is not included in the "organizations/peerOrganizations/org1.example.com/connection-org1.yaml" now. It seems that the gateway request way don't need that.

**Review by harrisob — APPROVED** [review]

**Comment by JunYang-CD** [comment]
This one pr solve this issue but then get another issue...
`ailed to evaluate transaction: Failed to submit: CreateAndSendTransaction failed: SendTransaction failed: orderers is nil`

**Comment by user00000001** [comment]
> This one pr solve this issue but then get another issue...
> `ailed to evaluate transaction: Failed to submit: CreateAndSendTransaction failed: SendTransaction failed: orderers is nil`

Which one?

**Comment by JunYang-CD** [comment]
> > This one pr solve this issue but then get another issue...
> > `ailed to evaluate transaction: Failed to submit: CreateAndSendTransaction failed: SendTransaction failed: orderers is nil`
> 
> Which one?

I mean this PR do solve the the issue it mean to solve. But then you will get another new issue which says " orderers is nil".

**Pull request merged**
